Add push notifications channel
Velir/dbt-ga4 pull request #152
Opened 2023-03-13 15:18 UTC by gblazq

## Description & motivation
The GA4 team has added the 'Mobile Push Notifications' channel group (see https://support.google.com/analytics/answer/9756891). This is an important channel for news outlets and other publishers that use push notifications.

I have renamed the channel from 'Mobile Push Notifications' to just 'Push Notifications' because 'push' is a common medium value for browser push notification services too.

This PR would close issue #151 with the channel name change.

## Checklist
- [x] I have verified that these changes work locally
- [na] I have updated the README.md (if applicable)
- [x] I have added tests & descriptions to my models (and macros if applicable)
- [x] I have run `dbt test` and `python -m pytest .` to validate existing tests

2023-03-13 18:03 UTC, dgitis requested changes
Thanks for fixing this up for everyone.

The [GA4 docs](https://support.google.com/analytics/answer/9756891?hl=en) give the following rules for the Mobile Push Notifications channel.

> Medium ends with "push"
>OR
>Medium contains "mobile" or "notification"
>OR
>Source exactly matches "firebase"

We want to default to matching these rules so you'll need to move 'push' into a separate regex to match the ends with rule (rather than push anywhere).

Additionally, `Push Notifications` should be  `Mobile Push Notifications`.

2023-03-14 07:30 UTC, gblazq commented
The regex matches the rules in the docs (`push$` ensures that `push` is only matched at the end of the string). As for the name, I had doubts and explained the reasons in issue #151. I have no problem with the required change, just wanted to point there because there's a comment in favour of the rename.

I should have set the PR as a draft before having more feedback on #151 to avoid duplicate discussions, sorry about that!

2023-03-14 20:27 UTC, adamribaudo-velir commented
@dgitis yea I think he's all set on the regex using `push$`. I don't have a really strong opinion on the default channel grouping name but I think if we need a tie breaker, we should go with what Google recommends. @gblazq do you mind making that 1 change? Then I think we can merge.

2023-03-14 22:45 UTC, dgitis commented
Sorry, I missed the `push$`. 

I also didn't see the issue where you had discussed _Push Notification_ versus _Mobile Push Notification_. I wouldn't approve a deviation from GA4 without a good reason, but it sounds like you have a decent reason for the change. 

I'll withdraw my change request.

2023-03-14 22:45 UTC, dgitis approved these changes

2023-03-15 11:07 UTC, merged